using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Persistence;

namespace Common;

public class GameInfosContextFactory
{
    public static readonly GameInfo GameInfoA = new()
    {
        Guid = Guid.NewGuid(),
        Width = 10,
        Height = 10,
        MinesCount = 10,
        Completed = false,
        Field = new List<List<int>>
        {
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            }
        },
        OriginField = new List<List<int>>
        {
            new()
            {
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            },
            new()
            {
                0,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0
            },
            new()
            {
                0,
                1,
                -1,
                1,
                1,
                1,
                1,
                1,
                1,
                1
            },
            new()
            {
                0,
                1,
                1,
                1,
                1,
                -1,
                2,
                2,
                -1,
                1
            },
            new()
            {
                0,
                0,
                0,
                0,
                1,
                1,
                2,
                -1,
                2,
                1
            },
            new()
            {
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                0
            },
            new()
            {
                1,
                1,
                0,
                0,
                1,
                2,
                3,
                -1,
                2,
                1
            },
            new()
            {
                -1,
                2,
                0,
                0,
                1,
                -1,
                -1,
                2,
                2,
                -1
            },
            new()
            {
                -1,
                2,
                0,
                0,
                1,
                2,
                2,
                1,
                1,
                1
            },
            new()
            {
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            },
        }
    };
    public static readonly GameInfo GameInfoB = new()
    {
        Guid = Guid.NewGuid(),
        Width = 10,
        Height = 10,
        MinesCount = 10,
        Completed = false,
        Field = new List<List<int>>
        {
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            },
            new()
            {
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2,
                -2
            }
        },
        OriginField = new List<List<int>>
        {
            new()
            {
                0,
                1,
                -1,
                1,
                0,
                1,
                1,
                1,
                0,
                0
            },
            new()
            {
                0,
                1,
                1,
                1,
                0,
                1,
                -1,
                1,
                1,
                1
            },
            new()
            {
                1,
                1,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                -1
            },
            new()
            {
                -1,
                2,
                1,
                1,
                0,
                0,
                0,
                0,
                1,
                1
            },
            new()
            {
                1,
                2,
                -1,
                1,
                0,
                0,
                0,
                0,
                0,
                0
            },
            new()
            {
                0,
                1,
                2,
                3,
                2,
                1,
                1,
                1,
                1,
                0
            },
            new()
            {
                0,
                0,
                1,
                -1,
                -1,
                1,
                2,
                -1,
                2,
                0
            },
            new()
            {
                0,
                1,
                2,
                3,
                2,
                1,
                2,
                -1,
                2,
                0
            },
            new()
            {
                0,
                1,
                -1,
                1,
                0,
                0,
                1,
                1,
                1,
                0
            },
            new()
            {
                0,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0
            }
        }
    };

    public static RepositoryDbContext Create()
    {
        var options = new DbContextOptionsBuilder<RepositoryDbContext>()
            .UseCosmos("https://apps.documents.azure.com:443/", "hyQNoQ4yhFqj1eEPX6PJJZwlRx4TWBGvtnnNd87ujKzZrKU6r5SzRzoa1k59w26ssKEQNCsXnaHmACDbTuE1tg==","minesweeper_test")
            .Options;

        var context = new RepositoryDbContext(options);

        // Clear DbSet
        context.GameInfos.RemoveRange(context.GameInfos.ToList());
        context.SaveChanges();
        //

        // Load test entities
        context.GameInfos.Add(GameInfoA);
        context.GameInfos.Add(GameInfoB);
        context.SaveChanges();
        //

        return context;
    }

    public static void Destroy(RepositoryDbContext context) =>
        context.Dispose();
}